#!/bin/bash

export PATH="$PATH:.:scripts"

set -e
set -o pipefail

mkdir -p stage
mkdir -p out-data

# collect survey data
#
./scripts/create_phenotype.py > stage/survey.tsv
mv stage/survey.tsv out-data/survey.tsv

# get user list
#
./scripts/grab_user.sh

# scrape Tapestry for phenotype information
# and file locations
#
./scripts/grab_profile_data.sh scratch/hid.list

# collection them into tsv files
#
./scripts/collect_profile_data.py

# insert into the untap.db.  Use it to
# generate the list of download urls for
# the report collection step.
#
cd stage
cat ../untap-db.xx | sqlite3 untap.db
echo "select human_id, report_url from uploaded_data where length(report_url)>0;" | sqlite3 untap.db > huid_report_url.csv
cd ..

# download, collect and de-duplicate the report data
# and insert into untap.db
#
cd ge-report
./generate
cat ../untap-db-report.xx | sqlite3 ../untap.db
cd ..



